#import "GPUEffectHaze3.h"
#import "GPUEffectColorfulCandy.h"
#import "GPUEffectSoftPop.h"
#import "GPUEffectSweetFlower.h"
#import "GPUEffectFaerieBloom.h"

#import "GPUEffectVintageFilm.h"
#import "GPUEffectHazelnut.h"
#import "GPUEffectVintage1.h"
#import "GPUEffectVintage2.h"
#import "GPUEffectOldTone.h"

#import "GPUEffectGoodMorning.h"
#import "GPUEffectWeekend.h"
#import "GPUEffectWarmAutumn.h"
#import "GPUEffectJoyful.h"

#import "GPUEffectCreamyNoon.h"
#import "GPUEffectGentleMemories.h"
#import "GPUEffectVanilla.h"
#import "GPUEffectSpringLight.h"

#import "GPUEffectSoftGlare.h"
#import "GPUEffectSunkissed.h"
#import "GPUEffectLeakLight.h"
#import "GPUEffectMysticGlow.h"
#import "GPUEffectFilmLightLeak.h"

#import "GPUEffectVividVintage.h"
#import "GPUEffectCavalleriaRusticana.h"
#import "GPUEffectDreamyVintage.h"
#import "GPUEffectSunsetCarnevale.h"

#import "GPUEffectBeachVintage.h"
#import "GPUEffectPinkBubbleTea.h"
#import "GPUEffectFaerieVintage.h"
#import "GPUEffectMarshmallow.h"

#import "GPUEffectMiami.h"
#import "GPUEffectSummers.h"
#import "GPUEffectGirder.h"
#import "GPUEffectSummerVacation.h"